FROM python:3.8

LABEL maintainer="Quantify Consortium"
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Amsterdam

ENV MPLBACKEND=agg # only necessary for unix that runs with headless display

CMD [ "/bin/bash" ]

RUN python -V  # Print out python version for debugging
RUN pip install virtualenv
RUN virtualenv venv
RUN source venv/bin/activate
RUN apt update
RUN apt install -y xvfb  # Sets up a headless display
RUN sleep 3

#RUN pip install --upgrade --upgrade-strategy eager -e .
#RUN pip install --upgrade --upgrade-strategy eager -r requirements_dev.txt
#RUN save the version of the packages installed for CI debugging
#RUN pip freeze --all > frozen-requirements.txt; cat frozen-requirements.txt
