FROM python:3.8

LABEL maintainer="Quantify Consortium"
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Amsterdam

# only necessary for unix that runs with headless display
ENV MPLBACKEND=agg

SHELL ["/bin/bash", "-c"]

# copy the build context files so that we can get the setup and pip
COPY /builds/quantify-os/quantify-core /builds

WORKDIR /builds
RUN ls

# Print out python version for debugging
RUN python -V
RUN pip install virtualenv
RUN virtualenv venv
RUN source venv/bin/activate
RUN apt update
# Sets up a headless display
RUN apt install -y xvfb

RUN pwd
RUN ls

RUN pip install --upgrade --upgrade-strategy eager -e .
RUN pip install --upgrade --upgrade-strategy eager -r requirements_dev.txt
#save the version of the packages installed for CI debugging
RUN pip freeze --all > frozen-requirements.txt; cat frozen-requirements.txt
